version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: cpa-app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - redis

    nginx:
        image: nginx:stable-alpine
        container_name: cpa-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: cpa-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cpa
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    redis:
        image: redis:alpine
        container_name: cpa-redis
        ports:
            - "6379:6379"

volumes:
    mysql_data:
